# Generated by Django 3.1.1 on 2021-01-05 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default='2021-01-01', verbose_name=datetime.datetime(2021, 1, 5, 14, 32, 44, 464909)),
        ),
    ]
