# Generated by Django 3.1.1 on 2021-01-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('POS_APP', '0006_auto_20210105_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custom',
        ),
    ]
