# Generated by Django 3.1.1 on 2021-01-06 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0007_delete_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date_added',
            field=models.DateField(default=datetime.date(2021, 1, 6)),
        ),
    ]
