# Generated by Django 3.1.1 on 2021-01-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0010_restaurant_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='order_date',
            field=models.DateField(default='06/01/2021 12:56:59'),
        ),
    ]
