# Generated by Django 3.1.1 on 2021-01-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0011_auto_20210106_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='Order_ID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_date',
            field=models.DateTimeField(default='06/01/2021 12:59:59'),
        ),
    ]
