# Generated by Django 3.1.1 on 2021-01-06 08:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0012_auto_20210106_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='Order_ID',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='id',
            field=models.AutoField(auto_created=True, default=100, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_date',
            field=models.DateField(default=datetime.date(2021, 1, 6)),
        ),
    ]
