# Generated by Django 3.1.1 on 2021-01-06 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0014_auto_20210106_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 6, 13, 19, 45, 151922)),
        ),
    ]
