# Generated by Django 3.1.1 on 2021-01-06 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0015_restaurant_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='item_1',
            field=models.CharField(blank=True, choices=[('1', 'helloo'), ('2', 'world')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 6, 13, 29, 11, 486525)),
        ),
    ]
