# Generated by Django 3.1.1 on 2021-01-06 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0017_auto_20210106_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='item_1',
            field=models.CharField(blank=True, choices=[('1', 'helloo'), ('2', 'world')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 6, 13, 35, 33, 987123)),
        ),
    ]
