# Generated by Django 3.1.1 on 2021-01-06 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0019_auto_20210106_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Total_Cost',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 6, 13, 53, 25, 368636)),
        ),
    ]
