# Generated by Django 3.1.1 on 2021-01-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS_APP', '0020_auto_20210106_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='Status',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='order_time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 6, 14, 26, 25, 336318)),
        ),
    ]
